const products = [
  {
    _id: '1',
    name: 'Floral Print Maxi Dress',
    image: 'https://media.istockphoto.com/id/1443335846/photo/happy-multiracial-japanese-woman-in-romantic-floral-maxi-dress-in-park.webp?b=1&s=170667a&w=0&k=20&c=451cxZIAaHj-RNSxGbLnWTm15fhfGggQplHL5Hn46xI=',
    description: 'Stay stylish with this beautiful floral print maxi dress. Perfect for a casual day out or a summer party.',
    brand: 'Fashionable',
    category: 'Dresses',
    price: 59.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Off-Shoulder Bodycon Dress',
    image: 'https://media.istockphoto.com/id/1445305043/photo/serie-of-studio-photos-of-young-female-model-in-elastic-black-and-white-classic-and-versatile.webp?b=1&s=170667a&w=0&k=20&c=gOCZclNl3kJIICHzhRQ87i6UGw0C76TmRr3MEAahZP8=',
    description: 'Make a statement with this elegant off-shoulder bodycon dress. The perfect choice for a night out or a special occasion.',
    brand: 'Glamorous',
    category: 'Dresses',
    price: 79.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Lace Cocktail Dress',
    image: 'https://media.istockphoto.com/id/185826933/photo/on-vacations.jpg?s=1024x1024&w=is&k=20&c=Jg3IJ2YCylm2FEoNS3gEN0KauwGKX87uUq4iLRF4bPI=',
    description: 'Step into elegance with this stunning lace cocktail dress. It features intricate lace detailing and a flattering fit.',
    brand: 'Sophisticate',
    category: 'Dresses',
    price: 129.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Wrap Midi Dress',
    image: 'https://media.istockphoto.com/id/1421871529/photo/serie-of-studio-photos-of-young-female-model-in-brown-tweed-dress-autumn-winter-fashion.jpg?s=1024x1024&w=is&k=20&c=_DwTNRnIdeVCmoKzRV8RZLEyBXc5AKxYili8FQufbPI=',
    description: 'Get a chic and trendy look with this stylish wrap midi dress. Perfect for both formal and casual occasions.',
    brand: 'Trendy',
    category: 'Dresses',
    price: 89.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Striped Summer Dress',
    image: 'https://media.istockphoto.com/id/543206886/photo/summer-cruise-and-happiness.jpg?s=1024x1024&w=is&k=20&c=o1VdjqgkYAB0nTPy0kJfJwWjGs6RkZ7cL58siTlKbDM=',
    description: 'Stay cool and fashionable this summer with this striped summer dress. It is lightweight and comfortable for hot weather.',
    brand: 'Summer Vibes',
    category: 'Dresses',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Little Black Dress',
    image: 'https://media.istockphoto.com/id/92661734/photo/young-woman-in-motion-black-dress.jpg?s=1024x1024&w=is&k=20&c=TKwZFIA6ynuiIgEx-FO7N7RoHQndIuACouifmgBH3nA=',
    description: 'Every woman needs a little black dress in her wardrobe. This classic piece is versatile and suitable for any occasion.',
    brand: 'Classic Chic',
    category: 'Dresses',
    price: 39.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Off-Shoulder Bodycon Dress',
    image: 'https://media.istockphoto.com/id/1445305043/photo/serie-of-studio-photos-of-young-female-model-in-elastic-black-and-white-classic-and-versatile.webp?b=1&s=170667a&w=0&k=20&c=gOCZclNl3kJIICHzhRQ87i6UGw0C76TmRr3MEAahZP8=',
    description: 'Make a statement with this elegant off-shoulder bodycon dress. The perfect choice for a night out or a special occasion.',
    brand: 'Glamorous',
    category: 'Dresses',
    price: 79.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '8',
    name: 'Lace Cocktail Dress',
    image: 'https://media.istockphoto.com/id/185826933/photo/on-vacations.jpg?s=1024x1024&w=is&k=20&c=Jg3IJ2YCylm2FEoNS3gEN0KauwGKX87uUq4iLRF4bPI=',
    description: 'Step into elegance with this stunning lace cocktail dress. It features intricate lace detailing and a flattering fit.',
    brand: 'Sophisticate',
    category: 'Dresses',
    price: 129.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Wrap Midi Dress',
    image: 'https://media.istockphoto.com/id/1421871529/photo/serie-of-studio-photos-of-young-female-model-in-brown-tweed-dress-autumn-winter-fashion.jpg?s=1024x1024&w=is&k=20&c=_DwTNRnIdeVCmoKzRV8RZLEyBXc5AKxYili8FQufbPI=',
    description: 'Get a chic and trendy look with this stylish wrap midi dress. Perfect for both formal and casual occasions.',
    brand: 'Trendy',
    category: 'Dresses',
    price: 89.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Striped Summer Dress',
    image: 'https://media.istockphoto.com/id/543206886/photo/summer-cruise-and-happiness.jpg?s=1024x1024&w=is&k=20&c=o1VdjqgkYAB0nTPy0kJfJwWjGs6RkZ7cL58siTlKbDM=',
    description: 'Stay cool and fashionable this summer with this striped summer dress. It is lightweight and comfortable for hot weather.',
    brand: 'Summer Vibes',
    category: 'Dresses',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '11',
    name: 'Little Black Dress',
    image: 'https://media.istockphoto.com/id/92661734/photo/young-woman-in-motion-black-dress.jpg?s=1024x1024&w=is&k=20&c=TKwZFIA6ynuiIgEx-FO7N7RoHQndIuACouifmgBH3nA=',
    description: 'Every woman needs a little black dress in her wardrobe. This classic piece is versatile and suitable for any occasion.',
    brand: 'Classic Chic',
    category: 'Dresses',
    price: 39.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'Wrap Midi Dress',
    image: 'https://media.istockphoto.com/id/1421871529/photo/serie-of-studio-photos-of-young-female-model-in-brown-tweed-dress-autumn-winter-fashion.jpg?s=1024x1024&w=is&k=20&c=_DwTNRnIdeVCmoKzRV8RZLEyBXc5AKxYili8FQufbPI=',
    description: 'Get a chic and trendy look with this stylish wrap midi dress. Perfect for both formal and casual occasions.',
    brand: 'Trendy',
    category: 'Dresses',
    price: 89.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  
];

export default products;
